CREATE TABLE account
(
    id VARCHAR(40) NOT NULL PRIMARY KEY,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP,
    name VARCHAR(40) NOT NULL,
    facebookUserId VARCHAR(40),
    googleUserId VARCHAR(40),
    isGuest BIT DEFAULT 0
)