CREATE TABLE account
(
    id VARCHAR(40) NOT NULL PRIMARY KEY,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP,
    name VARCHAR(255),
    facebookUserId VARCHAR(255),
    googleUserId VARCHAR(255),
    guest BIT DEFAULT 0
)