CREATE TABLE session
(
    id VARCHAR(40) NOT NULL PRIMARY KEY,
    ownerId VARCHAR(40) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP,
    expiresAt TIMESTAMP NULL DEFAULT NULL
)