CREATE TABLE lobby
(
    id VARCHAR(40) NOT NULL PRIMARY KEY,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP,
    name VARCHAR(40),
    player1 VARCHAR(40),
    player2 VARCHAR(40) NULL,
    closedAt TIMESTAMP NULL,
    isPrivate BIT DEFAULT 0
)