CREATE TABLE lobby
(
    id VARCHAR(40) NOT NULL PRIMARY KEY,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP,
    name VARCHAR(40),
    playerIdDark VARCHAR(40),
    playerIdLight VARCHAR(40) NULL,
    closedAt TIMESTAMP NULL,
    isPrivate BIT DEFAULT 0,
    playerDarkReady BIT DEFAULT 0,
    playerLightReady BIT DEFAULT 0
)